name: mail_push_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  device_info_plus: ^10.1.0
  uuid: ^4.5.0
  provider: ^6.0.0  # 상태 관리용
  # 인증 관련 (Google Sign-In, OAuth 등)
  google_sign_in: ^6.1.0
  googleapis_auth: ^1.6.0        # Google APIs 인증 패키지
  flutter_local_notifications: ^17.2.3  # 로컬 알림 패키지
  flutter_appauth: ^6.0.7 #outlook 인증 때 사용. 
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_secure_storage: ^9.2.4
  flutter_tts: ^3.6.3
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^5.0.0
  app_links: ^6.4.1
  android_intent_plus: ^5.3.1 # 최신 버전을 확인하고 사용하세요.
  package_info_plus: ^4.0.0
  permission_handler: ^10.4.0
  # HTTP 클라이언트 (API 통신)
  http: ^1.2.0
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  nb_utils: ^7.0.6
  google_fonts: ^6.3.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # 최신 버전 확인
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  image_path: "assets/icons/guardforce-logo.png"  # 아이콘 이미지 경로
  android: true
  ios: true
  remove_alpha_ios: true # iOS에서 투명도 제거 (필요 시)

flutter_native_splash:
  color: "#ffffff" # 배경색
  image: assets/splash.png # 스플래시 이미지 경로
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit

flutter:
  generate: true  # gen-l10n 활성화
  assets:
    - assets/sounds/siren.mp3
    - assets/icons/
    - assets/.env
    
  uses-material-design: true

