name: mail_push_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 인증 관련 (Google Sign-In, OAuth 등)
  google_sign_in: ^6.1.0
  googleapis_auth: ^1.6.0        # Google APIs 인증 패키지
  flutter_local_notifications: ^17.2.3  # 로컬 알림 패키지
  flutter_appauth: ^6.0.0 #outlook 인증 때 사용. 
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_secure_storage: ^9.2.4
  flutter_tts: ^3.6.3
  shared_preferences: ^2.5.3
  # HTTP 클라이언트 (API 통신)
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/sounds/siren.mp3
    - assets/icons/google_logo.png
    - assets/icons/outlook_logo.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
