name: mail_push_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.0
  # 인증 관련 (Google Sign-In, OAuth 등)
  google_sign_in: ^6.1.0
  googleapis_auth: ^1.6.0        # Google APIs 인증 패키지
  flutter_local_notifications: ^17.2.3  # 로컬 알림 패키지
  flutter_appauth: ^6.0.0 #outlook 인증 때 사용. 
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_secure_storage: ^9.2.4
  flutter_tts: ^3.6.3
  shared_preferences: ^2.5.3
  # HTTP 클라이언트 (API 통신)
  http: ^1.2.0
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # 최신 버전 확인
  flutter_native_splash: ^2.4.1

flutter_icons:
  image_path: "assets/icons/guardforce-logo.png"  # 아이콘 이미지 경로
  android: true
  ios: true

flutter_native_splash:
  color: "#ffffff" # 배경색
  image: assets/splash.png # 스플래시 이미지 경로
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  
flutter:
  assets:
    - assets/sounds/siren.mp3
    - assets/icons/google_logo.png
    - assets/icons/outlook_logo.png
    - assets/.env
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
