// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9U7IVcqugvg5nSrpuc5EnPbakcmsL2i0',
    appId: '1:1094752044540:web:237503a6b59ff9dee2de79',
    messagingSenderId: '1094752044540',
    projectId: 'mail-push-app-815d4',
    authDomain: 'mail-push-app-815d4.firebaseapp.com',
    storageBucket: 'mail-push-app-815d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArXZyBhGAhq3DoxFALJ0GDvccZM5kpGqQ',
    appId: '1:1094752044540:android:13aad88d4ed7dee6e2de79',
    messagingSenderId: '1094752044540',
    projectId: 'mail-push-app-815d4',
    storageBucket: 'mail-push-app-815d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5b1lwoqcZIo1dqZKOapCeqdJTyWXVeqk',
    appId: '1:1094752044540:ios:b9c54b88550ff1cde2de79',
    messagingSenderId: '1094752044540',
    projectId: 'mail-push-app-815d4',
    storageBucket: 'mail-push-app-815d4.firebasestorage.app',
    iosBundleId: 'com.secure.mailPushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5b1lwoqcZIo1dqZKOapCeqdJTyWXVeqk',
    appId: '1:1094752044540:ios:c80b4e860003292be2de79',
    messagingSenderId: '1094752044540',
    projectId: 'mail-push-app-815d4',
    storageBucket: 'mail-push-app-815d4.firebasestorage.app',
    iosBundleId: 'com.example.mailPushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9U7IVcqugvg5nSrpuc5EnPbakcmsL2i0',
    appId: '1:1094752044540:web:adb3a3b1a3f5a34ce2de79',
    messagingSenderId: '1094752044540',
    projectId: 'mail-push-app-815d4',
    authDomain: 'mail-push-app-815d4.firebaseapp.com',
    storageBucket: 'mail-push-app-815d4.firebasestorage.app',
  );

}